# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPath Testing Orch'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UiPath Testing Orch'
    testProjectPath: '$(Build.SourcesDirectory)'
    environment: 'EvanEnvironment'
    folderName: 'Evan Bruns'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'UiPath Testing Orch'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Evan Bruns'
    environments: 'EvanEnvironment'